#!/usr/bin/env python3
"""Generate DIFFERENCES.md: what the CPRT Rev 2 export contains vs this catalog,
and verify statement/discussion text matches CPRT after artifact repair."""
import json, re, glob, pathlib, collections, sys
ROOT = pathlib.Path(__file__).resolve().parent.parent
CPRT = sorted(glob.glob(str(ROOT / "sources/cprt_SP_800_171_2_0_0_*.json")))[-1]
DATE = re.search(r"(\d{4}-\d{2}-\d{2})", CPRT).group(1)
C = json.load(open(CPRT, encoding="utf-8"))["response"]["elements"]
B = json.load(open(ROOT / "catalog/nist-sp-800-171r2-combined-catalog.json", encoding="utf-8"))
sys.path.insert(0, str(ROOT / "scripts")); from build import repair_cprt_text, HYPHEN_REPAIRS

stmt = {e["element_identifier"]: e["text"] for e in C["elements"] if e["element_type"] == "requirement"}
disc = {e["element_identifier"][2:]: e["text"] for e in C["elements"] if e["element_type"] == "discussion"}
mine = {}
for g in B["catalog"]["groups"]:
    for c in g["controls"]:
        lab = next(p["value"] for p in c["props"] if p["name"] == "label")
        mine[lab] = (c["title"], next(p["prose"] for p in c["parts"] if p["name"] == "guidance"))
mismatch = [k for k in stmt if stmt[k].strip() != mine[k][0] or repair_cprt_text(disc[k]) != mine[k][1]]
assert not mismatch, f"catalog text diverges from CPRT after repair: {mismatch}"

runon = {k: len(re.findall(r"[a-z\)0-9]\.[A-Z]", v)) for k, v in disc.items()}
runon = {k: v for k, v in runon.items() if v}
orph = [(k, m) for k, v in disc.items() for m in re.findall(r"\w+- \w+|point-oforigin|cloudbased", v) if m != "identity- or"]
dbl = sum(v.count("  ") for v in disc.values())
key = lambda x: [int(i) for i in x.split(".")]

D = f"""# Differences from NIST's CPRT export of SP 800-171 Rev 2

Comparison of this catalog against the JSON export of SP 800-171 Revision 2 from the NIST Cybersecurity and Privacy Reference Tool (CPRT), document identifier `SP_800_171_2_0_0`, exported {DATE}. Generated by `scripts/diff_cprt.py`; nothing below is an opinion about CPRT's design.

## What CPRT provides for Rev 2

| Element | CPRT Rev 2 export | This catalog |
|---|---|---|
| Families | 14 | 14 |
| Requirements | 110 | 110 |
| Discussion text | 110 | 110 |
| Basic/derived requirement type | yes (relationship) | yes (`requirement-type` prop) |
| SP 800-171A assessment objectives | **none** | 320 |
| SP 800-171A assessment procedures (Examine/Interview/Test) | **none** | 110 |
| Format | CPRT JSON (elements + relationships) | OSCAL 1.1.2 catalog |
| Published in `usnistgov/oscal-content` | no | n/a |

The CPRT Rev 2 export contains no content from SP 800-171A. There is no NIST-published OSCAL rendering of SP 800-171 Rev 2. CPRT and `oscal-content` cover Rev 3 (`SP_800_171_3_0_0`), a different requirement set (97 requirements, 17 families, ODPs).

## Requirement and discussion text

This catalog's requirement statements and discussion text are taken verbatim from the CPRT Rev 2 export, then corrected only for the extraction artifacts listed below. `scripts/diff_cprt.py` asserts on every build that all 110 statements and all 110 discussions match CPRT exactly after those repairs.

### Artifacts present in the CPRT Rev 2 export

**Collapsed paragraph breaks** — sentences run together with no space where the source PDF had a paragraph boundary (e.g. `content.Organizations`). {sum(runon.values())} occurrences across {len(runon)} discussions: {', '.join(sorted(runon, key=key))}.

**Lost or orphaned hyphens at line breaks** — {len(orph)} occurrences:

| Control | CPRT text | Corrected |
|---|---|---|
""" + "".join(f"| {k} | `{m}` | `{HYPHEN_REPAIRS.get(m, m)}` |\n" for k, m in orph) + f"""
`identity- or role-based` (3.1.1) is a legitimate suspended hyphen and is left as-is.

**Double spaces** — {dbl} occurrences, collapsed.

### What the CPRT comparison found in this catalog's own baseline

Recorded for transparency: comparing against CPRT exposed errors in the pre-release baseline that schema validation had not caught — one requirement carrying the wrong text (3.13.12 had 3.13.11's statement and discussion), two truncated parentheticals (3.13.6, 3.13.7), and three statements using Rev 1 wording (3.1.21, 3.2.2, 3.5.4). All are fixed by building from the CPRT text. See CORRECTIONS.md.

## Not yet verified against a NIST machine-readable source

The 320 assessment objectives and 110 assessment procedures (SP 800-171A) are internally consistent and count-correct but have not been diffed against a NIST export. This section will be replaced when that comparison is done.
"""
(ROOT / "DIFFERENCES.md").write_text(D, encoding="utf-8")
print("DIFFERENCES.md written; catalog text matches CPRT after repair (110/110)")
