#!/usr/bin/env python3
"""Generate CORRECTIONS.md: field-level diff of sources/baseline vs catalog/."""
import json, re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
A = json.load(open(ROOT / "sources/baseline-2025-11-19.json", encoding="utf-8"))
B = json.load(open(ROOT / "catalog/nist-sp-800-171r2-combined-catalog.json", encoding="utf-8"))
REV1_WORDING = {"3.1.21", "3.2.2", "3.5.4"}
WRONG_CONTROL = {"3.13.12": "3.13.11"}

def lab(cid): return ".".join(str(int(x)) for x in cid.lstrip("_").split("."))
def n(s): return re.sub(r"\s+", " ", s).strip()
def flat(d):
    out = {}
    for g in d["catalog"]["groups"]:
        for c in g["controls"]:
            out[(c["id"], "title")] = c["title"]
            for p in c["parts"]:
                k = p["name"] if p["name"] in ("statement", "assessment") else p["id"]
                out[(c["id"], k)] = p["prose"]
    return out
def field(cid, f):
    return f.replace(cid + "_", "") if f.startswith("_") else f

a, b = flat(A), flat(B)
rows, ws = [], 0
for k in sorted(set(a) | set(b), key=lambda k: ([int(x) for x in lab(k[0]).split(".")], k[1])):
    va, vb = a.get(k), b.get(k)
    if va == vb: continue
    cid, f = lab(k[0]), field(k[0], k[1])
    if va is None:
        rows.append((cid, f, "added (SP 800-171A)")); continue
    t = []
    if f in ("title", "statement"):
        if cid in WRONG_CONTROL: t.append(f"**wrong requirement text** (carried {WRONG_CONTROL[cid]}); replaced")
        elif cid in REV1_WORDING: t.append("Rev 1 wording; replaced with Rev 2")
        elif len(n(vb)) > len(n(va)) + 3: t.append("truncated text restored")
        elif n(va).replace("(", "").replace(")", "") == n(vb).replace("(", "").replace(")", ""): t.append("parentheses restored")
        elif n(va).replace(",", "") == n(vb).replace(",", ""): t.append("comma restored")
        elif n(vb) == n(va).rstrip(".") + ".": t.append("terminal period")
    elif f.startswith("obj") or f == "assessment":
        t.append("replaced with SP 800-171A text")
    else:
        if cid in WRONG_CONTROL and f == "disc": t.append(f"**wrong discussion text** (carried {WRONG_CONTROL[cid]}); replaced")
        if "â€" in va: t.append("encoding repaired (curly quotes restored)")
        if re.search(r"[a-z\)]\.[A-Z]", va): t.append("paragraph spacing")
        if "  " in va: t.append("double space")
        if any(x in va for x in ("cloudbased", "in- house", "point-oforigin")): t.append("hyphenation")
    if not t and n(va) == n(vb):
        ws += 1; continue
    rows.append((cid, f, ", ".join(t) or "text changed"))

L = ["# Corrections: baseline (2025-11-19) → " + B["catalog"]["metadata"]["version"], "",
     "Field-level diff between the internal baseline and the built catalog, generated by `scripts/diff_baseline.py`. Requirement statements and discussion text are taken from NIST's CPRT export of SP 800-171 Rev 2 (see DIFFERENCES.md); assessment objectives and procedures are from SP 800-171A.", "",
     "**Structural additions (all 110 controls):** `label`, `sort-id`, and `requirement-type` (basic/derived) props; `class: family` on every group.", "",
     "**SP 800-171A layer:** every assessment objective and procedure is now taken from the SP 800-171A PDF (`sources/sp800-171a-extracted.json`). Rows below marked 'replaced with SP 800-171A text' are fields whose baseline wording differed from the PDF; identical fields are not listed. This includes 3.1.19's previously missing procedure and 3.6.3's previously missing TEST.", "",
     "| Control | Field | Change |", "|---|---|---|"]
L += [f"| {r[0]} | {r[1]} | {r[2]} |" for r in rows]
L += ["", f"_Trailing-whitespace-only changes ({ws} fields) omitted._"]
(ROOT / "CORRECTIONS.md").write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"CORRECTIONS.md: {len(rows)} rows")
